// Application constants and magic numbers

export const UI_CONSTANTS = {
  DEBOUNCE_DELAY_MS: 300,
  SIDEBAR_MIN_WIDTH: 280,
  SIDEBAR_MAX_WIDTH: 500,
  FILE_INPUT_CLICK_DELAY_MS: 50,
  INPUT_CLEAR_DELAY_MS: 100,
  PROGRESS_MAX_PERCENT: 100,
  PROGRESS_MIN_PERCENT: 0,
  IGNORED_ITEMS_MAX: 1000,
  SCAN_FILES_YIELD_INTERVAL: 25,
  FILE_READING_YIELD_INTERVAL: 100,
  PROGRESS_THROTTLE_MS: 500,
  URL_REVOKE_DELAY_MS: 100,
};

export const EXPORT_CONSTANTS = {
  TXT_CHUNK_SIZE: 50,
  ZIP_CHUNK_SIZE: 40,
  ZIP_MAX_FILES: 65535,
  PROGRESS_PERCENT_READING: 50,
  PROGRESS_PERCENT_READY: 100,
};

export const TREE_CONSTANTS = {
  DEFAULT_EXPAND_DEPTH: 2,
  INDENT_PER_LEVEL: 16,
  BASE_PADDING: 8,
  TOGGLE_WIDTH: 20,
};
