// Web Worker for heavy export tasks. No network dependencies.

function formatBytes(bytes) {
  if (!bytes) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return (bytes / 1024 ** i).toFixed(i ? 1 : 0) + " " + units[i];
}

let cancelled = false;
let activeType = "";
let exportOptions = {};
let fileIndex = [];
let zipEntries = [];

self.onmessage = async function (e) {
  const { type, files, action, chunkIndex, totalChunks, options } = e.data;

  if (action === "start") {
    cancelled = false;
    activeType = type;
    exportOptions = options || {};
    fileIndex = e.data.fileIndex || [];
    zipEntries = [];
    return;
  }

  if (action === "cancel") {
    cancelled = true;
    self.postMessage({ type: "cancelled" });
    return;
  }

  if (action !== "processChunk") return;

  try {
    if (cancelled) {
      self.postMessage({ type: "cancelled" });
      return;
    }

    if (type === "txt") {
      processTxtChunk(files, chunkIndex, totalChunks);
    } else if (type === "ai") {
      processAiChunk(files, chunkIndex, totalChunks);
    } else if (type === "zip") {
      await processZipChunk(files, chunkIndex, totalChunks);
    } else {
      self.postMessage({ type: "error", data: `Unknown export type: ${type}` });
    }
  } catch (err) {
    if (!cancelled) {
      self.postMessage({ type: "error", data: err.message });
    }
  }
};

function processTxtChunk(files, chunkIndex, totalChunks) {
  const chunks = [];
  const encoder = new TextEncoder();

  for (const f of files) {
    const header = `// ============================================\n// File: ${f.name}\n// Path: ${f.path}\n// Size: ${formatBytes(f.size)}\n// ============================================\n\n`;
    chunks.push(encoder.encode(header));
    chunks.push(f.data);
    chunks.push(encoder.encode("\n\n\n"));
  }

  postArrayBuffer("txtChunk", chunks, chunkIndex, totalChunks);
  postProgress("Combining files", chunkIndex, totalChunks);
}

function processAiChunk(files, chunkIndex, totalChunks) {
  const chunks = [];
  const encoder = new TextEncoder();

  if (chunkIndex === 1) {
    chunks.push(encoder.encode(buildAiHeader()));
  }

  for (const f of files) {
    chunks.push(encoder.encode(renderAiFile(f)));
  }

  if (chunkIndex === totalChunks) {
    chunks.push(
      encoder.encode(
        "\n---\nGenerated by Code Snapshot. All processing happened locally in the browser.\n",
      ),
    );
  }

  postArrayBuffer("aiChunk", chunks, chunkIndex, totalChunks);
  postProgress("Preparing AI snapshot", chunkIndex, totalChunks);
}

async function processZipChunk(files, chunkIndex, totalChunks) {
  for (const f of files) {
    zipEntries.push({
      path: sanitizeZipPath(f.path),
      data: f.data,
    });
  }

  postProgress("Collecting ZIP entries", chunkIndex, totalChunks);

  if (chunkIndex < totalChunks) {
    self.postMessage({ type: "chunkComplete", chunkIndex, totalChunks });
    return;
  }

  self.postMessage({
    type: "progress",
    percent: 96,
    text: "Building ZIP archive...",
  });
  const zipped = await createZip(zipEntries);
  self.postMessage(
    {
      type: "zipChunk",
      data: zipped.buffer,
      chunkIndex,
      totalChunks,
    },
    [zipped.buffer],
  );
}

function postArrayBuffer(messageType, chunks, chunkIndex, totalChunks) {
  const blob = new Blob(chunks);
  blob.arrayBuffer().then((arrayBuffer) => {
    self.postMessage(
      {
        type: messageType,
        data: arrayBuffer,
        chunkIndex,
        totalChunks,
      },
      [arrayBuffer],
    );
  });
}

function postProgress(label, chunkIndex, totalChunks) {
  const percent = Math.round(20 + (chunkIndex / totalChunks) * 75);
  self.postMessage({
    type: "progress",
    percent,
    text: `${label}... ${chunkIndex}/${totalChunks}`,
  });
}

function buildAiHeader() {
  const includedSize = fileIndex.reduce((sum, f) => sum + (f.size || 0), 0);
  const warnings = fileIndex.reduce(
    (sum, f) => sum + ((f.warnings && f.warnings.length) || 0),
    0,
  );
  const tree = buildDirectoryTree(fileIndex.map((f) => f.path));
  const indexRows = fileIndex
    .map((f, index) => {
      const notes = [];
      if (f.category) notes.push(f.category);
      if (f.warnings?.length) notes.push(`${f.warnings.length} warning(s)`);
      return `| ${index + 1} | ${escapeMarkdownCell(f.path)} | ${formatBytes(f.size)} | ${escapeMarkdownCell(notes.join(", ") || "-")} |`;
    })
    .join("\n");

  return `# Code Snapshot AI Handoff

## Project Summary
- Generated: ${exportOptions.generatedAt || new Date().toISOString()}
- Files included: ${fileIndex.length}
- Included size: ${formatBytes(includedSize)}
- Source files loaded: ${exportOptions.totalFiles ?? fileIndex.length}
- Excluded files: ${exportOptions.excludedFiles ?? 0}
- Ignored items: ${exportOptions.ignoredItems ?? 0}
- Local warning count: ${exportOptions.warningCount ?? warnings}

## Export Settings
- Mode: AI Snapshot
- Search filter: ${exportOptions.filters?.query || "(none)"}
- Category filter: ${exportOptions.filters?.category || "all"}
- Sort order: ${exportOptions.filters?.sort || "path-asc"}

## Directory Tree
\`\`\`text
${tree}
\`\`\`

## Included File Index
| # | Path | Size | Notes |
|---:|---|---:|---|
${indexRows || "| - | - | - | - |"}

## File Contents
`;
}

function renderAiFile(fileInfo) {
  const warnings = fileInfo.warnings || [];
  const warningText = warnings.length
    ? warnings
        .map((warning) => `- ${warning.severity}: ${warning.message}`)
        .join("\n")
    : "- none";

  if (looksBinary(fileInfo.data)) {
    return `
### ${fileInfo.path}

- Size: ${formatBytes(fileInfo.size)}
- Category: ${fileInfo.category || "unknown"}
- Local warnings:
${warningText}

\`\`\`text
[Binary or unsupported content omitted from AI snapshot]
\`\`\`
`;
  }

  const decoder = new TextDecoder("utf-8", { fatal: false });
  const text = decoder.decode(fileInfo.data);
  const fence = makeFence(text);
  return `
### ${fileInfo.path}

- Size: ${formatBytes(fileInfo.size)}
- Category: ${fileInfo.category || "unknown"}
- Local warnings:
${warningText}

${fence}${languageFromPath(fileInfo.path)}
${text}
${fence}
`;
}

function buildDirectoryTree(paths) {
  const root = { dirs: new Map(), files: [] };

  for (const path of [...paths].sort((a, b) => a.localeCompare(b))) {
    const parts = path.split("/").filter(Boolean);
    let node = root;
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i];
      if (!node.dirs.has(part)) {
        node.dirs.set(part, { dirs: new Map(), files: [] });
      }
      node = node.dirs.get(part);
    }
    node.files.push(parts[parts.length - 1] || path);
  }

  const lines = [];
  const walk = (node, prefix = "") => {
    const dirs = Array.from(node.dirs.entries()).sort(([a], [b]) =>
      a.localeCompare(b),
    );
    const files = node.files.sort((a, b) => a.localeCompare(b));
    dirs.forEach(([name, child], index) => {
      const isLast = index === dirs.length - 1 && files.length === 0;
      lines.push(`${prefix}${isLast ? "+-- " : "|-- "}${name}/`);
      walk(child, `${prefix}${isLast ? "    " : "|   "}`);
    });
    files.forEach((name, index) => {
      const isLast = index === files.length - 1;
      lines.push(`${prefix}${isLast ? "+-- " : "|-- "}${name}`);
    });
  };

  walk(root);
  return lines.join("\n") || ".";
}

function makeFence(content) {
  let fence = "```";
  while (content.includes(fence)) {
    fence += "`";
  }
  return fence;
}

function languageFromPath(path) {
  const extension = path.toLowerCase().split(".").pop() || "";
  const map = {
    js: "javascript",
    jsx: "jsx",
    ts: "typescript",
    tsx: "tsx",
    mjs: "javascript",
    cjs: "javascript",
    py: "python",
    rb: "ruby",
    go: "go",
    rs: "rust",
    java: "java",
    kt: "kotlin",
    swift: "swift",
    c: "c",
    h: "c",
    cpp: "cpp",
    hpp: "cpp",
    cs: "csharp",
    php: "php",
    sh: "bash",
    ps1: "powershell",
    html: "html",
    css: "css",
    scss: "scss",
    json: "json",
    yaml: "yaml",
    yml: "yaml",
    md: "markdown",
    sql: "sql",
    xml: "xml",
  };
  return map[extension] || "";
}

function looksBinary(data) {
  const limit = Math.min(data.length, 8000);
  if (!limit) return false;
  let suspicious = 0;
  for (let i = 0; i < limit; i++) {
    const value = data[i];
    if (value === 0) return true;
    if (value < 7 || (value > 14 && value < 32)) suspicious++;
  }
  return suspicious / limit > 0.08;
}

function escapeMarkdownCell(value) {
  return String(value ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\n/g, " ");
}

function sanitizeZipPath(path) {
  return String(path || "file")
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/(^|\/)\.\.(\/|$)/g, "$1_$2");
}

async function createZip(entries) {
  if (entries.length > 65535) {
    throw new Error(
      "ZIP export supports up to 65,535 files in this browser build",
    );
  }

  const encoder = new TextEncoder();
  const localParts = [];
  const centralParts = [];
  let offset = 0;
  const dateParts = getDosDateTime(new Date());

  for (const entry of entries) {
    const nameBytes = encoder.encode(entry.path);
    const data = entry.data;
    const compressed = await compressForZip(data);
    const crc = crc32(data);

    if (
      data.length > 0xffffffff ||
      compressed.data.length > 0xffffffff ||
      offset > 0xffffffff
    ) {
      throw new Error("ZIP export is too large for the local ZIP writer");
    }

    const localHeader = new Uint8Array(30 + nameBytes.length);
    const localView = new DataView(localHeader.buffer);
    localView.setUint32(0, 0x04034b50, true);
    localView.setUint16(4, 20, true);
    localView.setUint16(6, 0x0800, true);
    localView.setUint16(8, compressed.method, true);
    localView.setUint16(10, dateParts.time, true);
    localView.setUint16(12, dateParts.date, true);
    localView.setUint32(14, crc, true);
    localView.setUint32(18, compressed.data.length, true);
    localView.setUint32(22, data.length, true);
    localView.setUint16(26, nameBytes.length, true);
    localHeader.set(nameBytes, 30);

    const centralHeader = new Uint8Array(46 + nameBytes.length);
    const centralView = new DataView(centralHeader.buffer);
    centralView.setUint32(0, 0x02014b50, true);
    centralView.setUint16(4, 20, true);
    centralView.setUint16(6, 20, true);
    centralView.setUint16(8, 0x0800, true);
    centralView.setUint16(10, compressed.method, true);
    centralView.setUint16(12, dateParts.time, true);
    centralView.setUint16(14, dateParts.date, true);
    centralView.setUint32(16, crc, true);
    centralView.setUint32(20, compressed.data.length, true);
    centralView.setUint32(24, data.length, true);
    centralView.setUint16(28, nameBytes.length, true);
    centralView.setUint32(42, offset, true);
    centralHeader.set(nameBytes, 46);

    localParts.push(localHeader, compressed.data);
    centralParts.push(centralHeader);
    offset += localHeader.length + compressed.data.length;
  }

  const centralOffset = offset;
  const centralSize = centralParts.reduce((sum, part) => sum + part.length, 0);
  if (centralOffset > 0xffffffff || centralSize > 0xffffffff) {
    throw new Error("ZIP export is too large for the local ZIP writer");
  }

  const end = new Uint8Array(22);
  const endView = new DataView(end.buffer);
  endView.setUint32(0, 0x06054b50, true);
  endView.setUint16(8, entries.length, true);
  endView.setUint16(10, entries.length, true);
  endView.setUint32(12, centralSize, true);
  endView.setUint32(16, centralOffset, true);

  return concatUint8Arrays([...localParts, ...centralParts, end]);
}

async function compressForZip(data) {
  if (typeof CompressionStream !== "function" || data.length < 256) {
    return { data, method: 0 };
  }

  try {
    const stream = new Blob([data])
      .stream()
      .pipeThrough(new CompressionStream("deflate-raw"));
    const compressed = new Uint8Array(await new Response(stream).arrayBuffer());
    if (compressed.length && compressed.length < data.length) {
      return { data: compressed, method: 8 };
    }
  } catch {
    // Store without compression when the browser does not support raw deflate.
  }

  return { data, method: 0 };
}

function concatUint8Arrays(parts) {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    output.set(part, offset);
    offset += part.length;
  }
  return output;
}

function getDosDateTime(date) {
  const year = Math.max(1980, date.getFullYear());
  const dosTime =
    (date.getHours() << 11) |
    (date.getMinutes() << 5) |
    Math.floor(date.getSeconds() / 2);
  const dosDate =
    ((year - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
  return { date: dosDate, time: dosTime };
}

let crcTable = null;

function crc32(data) {
  if (!crcTable) {
    crcTable = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) {
        c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      }
      crcTable[n] = c >>> 0;
    }
  }

  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) {
    crc = crcTable[(crc ^ data[i]) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
